algoritmo "semnome"
// Função :
// Autor :
// Data : 26/08/2021
// Seção de Declarações 
var
N :INTEIRO
PROCEDIMENTO PAROUIMPAR( V : INTEIRO)
inicio
  ESCREVAL(" O VALOR DE V E ", V)
 ESCREVAL(" O VALOR DE N E ", N)
SE(V%2=0 ) ENTAO
 ESCREVAL(" O NUMERO ", V, " E PAR")
 SENAO
 ESCREVAL(" O NUMERO " , V , " E IMPAR")
 FIMSE
 FIMPROCEDIMENTO
 INICIO
 ESCREVA(" DIGITE UM NUMERO : ")
 LEIA (N)
 PAROUIMPAR(N)

 fimalgoritmo
